[build]
  publish = ".next"
  command = "yarn build:prod"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@sentry/netlify-build-plugin"

  [plugins.inputs]
    sentryOrg = "wesolowskidev"
    sentryProject = "nextjs"